import type { ReferralIncome } from "../../types/referral.types";

import EmptyState from "./EmptyState";
import styles from "./Table.module.css";

interface Props {
  data: ReferralIncome[];
}

const ReferralIncomeTable = ({
  data,
}: Props) => {

  if (!data.length) {
    return (
      <EmptyState
        message="No referral income found"
      />
    );
  }

  return (
    <div className={styles.responsive}>
      <table>
        <thead>
          <tr>
            <th>
              Generated By
            </th>

            <th>
              Level
            </th>

            <th>
              Income
            </th>

            <th>
              Date
            </th>
          </tr>
        </thead>

        <tbody>
          {data.map(
            (item) => (
              <tr
                key={
                  item._id
                }
              >
                <td>
                  {
                    item
                      .generatedByUser
                      .fullName
                  }
                </td>

                <td>
                  {
                    item.referralLevel
                  }
                </td>

                <td>
                  Rs.
                  {
                    item.incomeAmount
                  }
                </td>

                <td>
                  {new Date(
                    item.date
                  ).toLocaleDateString()}
                </td>
              </tr>
            )
          )}
        </tbody>
      </table>
    </div>
  );
};

export default ReferralIncomeTable;
